### ISSUE TITLE
Estimate sale hitting URL 2 times combine it to 1 to reduce the latency of data. 

### ISSUE THREAD

**Issue by Juned-the-programmer** [Juned-the-programmer/Single-Inventory-App#2]
In Estimate sale operation we are hitting 2 different URL for 2 operations which are selling_price and previous_discount which we can combine it into single URL from which we can reduce the latency of data as it is hitting single URL and didn't have to wait for another to complete it processing.

**Comment by Atif1727** [comment]
i am picking up this issue

**Comment by Juned-the-programmer** [comment]
**NOTE** : Branch Name [ES001]
